version: '3'

services:

  redis:
      container_name: redis
      image: redis:7
      ports:
        - "6379:6379"
      volumes:
        - redis:/data
  db:
    image: postgres:14.3
    restart: always
    ports:
      - "6432:5432"
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    container_name: culturaDB
    volumes:
      - ./postgres:/var/lib/postgresql/data

volumes:
  redis: